package br.principal;

public class Detalhes extends javax.swing.JFrame {

    /**
     * Creates new form DetalhesDia1
     */
    public Detalhes() {
        initComponents();  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        oficinas = new javax.swing.JList<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        comboDetalhes = new javax.swing.JComboBox<>();
        jToggleButton2 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(oficinas);

        jToggleButton1.setText("Mostrar detalhes");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        comboDetalhes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia 1", "Dia 2", "Dia 3" }));
        comboDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDetalhesActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Imagem do dia");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("SAIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(comboDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(273, 273, 273))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(comboDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton1)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (comboDetalhes.getSelectedIndex() == 0){
            Oficinas details1 = new Oficinas("7:00 ", "Prof. Martinho ", "Uma exposição fotográfica que revela a beleza oculta nos detalhes do cotidiano, capturando momentos singulares através da lente, convidando você a enxergar o ordinário de forma extraordinária");
            Oficinas details2 = new Oficinas("7:40 ", " ", "Damos início ao evento Novembro Negro e Indígena, celebrando e reconhecendo as culturas, lutas e contribuições dessas comunidades. Junte-se a nós nesta jornada de conscientização e respeito");
            Oficinas details3 = new Oficinas("10:00 ", "RAPPER LUAN RICKSON ", "Explore culturas em nossa apresentação única, onde música, dança e narrativas se entrelaçam. Uma experiência que celebra a diversidade e nos conecta por meio da arte.");
           Oficinas details4 = new Oficinas("10:45 ", " ", "Explore a moda que celebra a diversidade em nosso desfile exclusivo. Estilo, identidade e cultura se unem em uma passarela única.");
           Oficinas details5 = new Oficinas("11:05 ", "Zé das Congas ", "Seja parte da ação em nossa apresentação interativa. Conecte-se, participe e crie memórias únicas neste momento especial!"); 
           Oficinas details6 = new Oficinas("13:50 ", "RAPPER LUIZ GUILHERME ", "Explore culturas em nossa apresentação única, onde música, dança e narrativas se entrelaçam. Uma experiência que celebra a diversidade e nos conecta por meio da arte.");
           Oficinas details7 = new Oficinas("15:30 ", "Prof. Martinho ", "Descubra o mundo da fotografia em nossa oficina interativa. Equipamento na mão, técnicas na ponta dos dedos – mergulhe na arte de capturar momentos inesquecíveis");
           Oficinas details8 = new Oficinas("15:30 ", "Luiz Gustavo ", "Yoté é um jogo de tabuleiro de origem africana popular no Senegal, Mali, Guiné e Gâmbia. Nesta oficina, iremos criar uma versão digital deste jogo de tabuleiro. Por meio desta abordagem, busca-se conhecer mais sobre jogos africanos que inspiraram diversos jogos populares hoje em dia. Além disso, possibilita conhecer e reconhecer a importância do continente africado para o desenvolvimento de diversas áreas do entretenimento, ciência, pensamento lógico e outros. Iremos implementar este jogo do zero, sem uso de frameworks, apenas utilizando HTML, CSS e Vanilla Javascript. Para o melhor aproveitamento da oficina, exige-se que o estudante tenha conhecimento consolidado em programação.");
           Oficinas details9 = new Oficinas("15:30 ", "Martinho Souza ", "Traçado e pintura de rostos a partir das características étnicas de traços anatômicos africanos e indígenas.");
           Oficinas details10 = new Oficinas("15:30 ", " ", "Participe da nossa oficina 'Reconhecimento Facial e Raça: Uma Análise através do Documentário Coded'. Explore as complexidades, desafios e impactos dessa tecnologia em uma sessão educativa e esclarecedora.");
           String[] detalhes = {details1.getDetalhes(), details2.getDetalhes(), details3.getDetalhes(), details4.getDetalhes(), details5.getDetalhes(), details6.getDetalhes(),details7.getDetalhes(), details8.getDetalhes(), details9.getDetalhes(), details10.getDetalhes()};
            oficinas.setListData(detalhes);
        }
        else if (comboDetalhes.getSelectedIndex() == 1){
            Oficinas details11 = new Oficinas("7:00 ", " ", "Descubra o talento e a inovação dos estudantes durante as apresentações do evento integrado. Nossa programação abrange uma variedade de temas, desde projetos acadêmicos até conquistas notáveis. Junte-se a nós para uma jornada educativa, onde os próprios estudantes compartilharão experiências, pesquisas e realizações que enriquecem nossa comunidade acadêmica.");
            String[] detalhes = {details11.getDetalhes()};
            oficinas.setListData(detalhes);
        }
        else if (comboDetalhes.getSelectedIndex() == 2){
            Oficinas details12 = new Oficinas("8:00 ", " ", "Mostras teatrais, Música, Salas Temáticas, Apresentações e outros.");
            String[] detalhes = {details12.getDetalhes()};
            oficinas.setListData(detalhes);
        }
  
        else {
            
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        if (comboDetalhes.getSelectedIndex() == 0){
            imagensDiaUm imagens1 = new imagensDiaUm();
            imagens1.setVisible(true);  
        }
        else if (comboDetalhes.getSelectedIndex() == 1){
            imagensDiaDois imagens2 = new imagensDiaDois();
            imagens2.setVisible(true);
        }
        else if (comboDetalhes.getSelectedIndex() == 2){
            imagensDiaTres imagens3 = new imagensDiaTres();
            imagens3.setVisible(true);
        }
        else {
            
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void comboDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDetalhesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDetalhesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Detalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Detalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Detalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Detalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Detalhes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboDetalhes;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JList<String> oficinas;
    // End of variables declaration//GEN-END:variables
}
